version: '3.2'

services:
  backend:
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
        - CACHEBUST=${CACHEBUST:-1}
      dockerfile: backend/Dockerfile
    image: skillcrafts-backend
    container_name: skillcrafts_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - postgresql
    networks:
      - app-network

  test_framework:
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
        - CACHEBUST=${CACHEBUST:-1}
      dockerfile: test_framework/Dockerfile
    image: test_framework-test
    container_name: test_framework_service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BASE_URL=${BASE_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "8001:8001"
    volumes:
      - test_framework_static_volume:/app/staticfiles
      - test_framework_media_volume:/app/media
    networks:
      - app-network

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: skillcrafts_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app-network

  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: allure
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5    # частота проверки новых результатов
      KEEP_HISTORY: 1                   # хранить историю
      KEEP_HISTORY_LATEST: 25           # количество отчётов в истории
      # В продакшене нужно настроить секьюрный токен и пользователя
      # SECURITY_USER: allure_admin
      # SECURITY_PASS: ************
      # SECURITY_ENABLED: 1
    volumes:
      - allure-results:/app/allure-results
      - allure-reports:/app/default-reports
    depends_on:
      - backend
    networks:
      - app-network

  worker:
    image: test_framework-test
    container_name: worker_service
    restart: unless-stopped
    command: celery -A skillcrafts_test_framework worker -E -n test_fr_worker@%h --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - test_framework_media_volume:/app/media
    depends_on:
      - test_framework
    networks:
      - app-network

  flower:
    image: test_framework-test
    container_name: flower_service
    restart: unless-stopped
    command: celery -A skillcrafts_test_framework flower
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "5555:5555"
    depends_on:
      - test_framework
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
  redis_data:
  allure-results:
  allure-reports:
  test_framework_static_volume:
  test_framework_media_volume:
